apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
      version: v1
  template:
    metadata:
      labels:
        app: userservice
        version: v1
    spec:
      containers:
        - name: userservice
          image: jtvdheijden/kwetter-backend-userservice
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: 50m
            requests:
              cpu: 10m
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
  labels:
    app: userservice
    service: userservice
spec:
  type: ClusterIP
  ports:
    - name: "http-5000"
      port: 5000
      targetPort: 5000
  selector:
    app: userservice