apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      version: v1
  template:
    metadata:
      labels:
        app: gateway
        version: v1
    spec:
      containers:
        - name: gateway
          image: jtvdheijden/kwetter-backend-gatewayservice
          imagePullPolicy: "Always"
          ports:
            - containerPort: 5020
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    service: gateway
spec:
  type: LoadBalancer
  ports:
    - name: "http-5020"
      port: 5020
      targetPort: 5020
  selector:
    app: gateway